// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbbjdxgxcoinnpeogepy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiYmpkeGd4Y29pbm5wZW9nZXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTczNTMsImV4cCI6MjA2MjkzMzM1M30.5owOpdrZZJLl3UTcT6juC022H69zCKJGwfPVkjz-mV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);